steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--tag=gcr.io/roi-takeoff-user73/pets-api:2"
      - "--file=./api/ops/pets/Dockerfile"
      - .
images:
  - "gcr.io/roi-takeoff-user73/pets-api:2"